name: Build and Publish to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Prepare files from repository
      uses: actions/checkout@v2
      
    - name: Set up Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    
    - name: Install NPM dependencies
      run: npm ci
      
    - name: Build source files
      run: npm run build

    - name: Configure git credentials for pushing
      run: |
        git config user.name "GitHub Pages Deploy"
        git config user.email "github-actions@github.com"
      
    - name: Publish to GitHub Pages ğŸ‰ï¸
      run: npm run deploy
